from enum import StrEnum
from pathlib import Path
from typing import Self


LIB_ID_URL_KEY = 'lib_id'
TARGET_ID_URL_KEY = 'target_id'
STATE_ID_URL_KEY = 'state_id'
SUB_ID_URL_KEY = 'substrate_id'
DOMAIN = 'localhost:8501'
FILE_STORAGE_PATH = Path(
    r"C:\Users\Camille.RAHI\Documents\Documents\Code\dahu-2-storage")
FILM_INIT_STATE = 'As deposited'
PATTERN_IMAGE_PATH = 'pages/logic/images'
NEW_TARGET = 'NOT BASED ON AN EXISTING TARGET'
PIXEL_COORDS = 'pixel_selection'
REDIRECT_PATH_URL_KEY = 'redirect_path'
ID_KEY_URL_KEY = 'id_key'
ID_VALUE_URL_KEY = 'id_value'
DB_UNIT_SYSTEM = 'SI'

class CookieKeys(StrEnum):
    """Keys are hard coded random strings, so that if we rename the variable
    for an update, we'll still access the value from old version with the
    same key in the cookie."""

    LAST_EMAIL_USED = '4f89qv6sdw531xcs6qqf4c5q6d8zs4cD'
    LIB_FILTERS = 'f4ze86sd4ce1v68rrf46sdw1cqz568fc4'
    TARGET_FILTERS = 'd48qz6f4cdsv1r3e54g68e6rq43q1dz'
    SUBSTRATE_FILTERS = 'e46vsq98f4z5618af9ez4sxdq4658f4s'


class SessionKeys(StrEnum):
    PATCH_FORMS = 'patch_forms_key'
    PAGE_URL_PATH = 'page_url_path_key'
    SUBSTRATE_LAYERS = 'substrate_layer_forms_key'
    SUBSTRATE_LAYER_FORMS = 'substrate_layer_forms_key'
    FILM_LAYERS = 'film_layers_key'
    SPUTTERING_SYSTEM = 'sputter_system_key'
    LAYER_DATA = 'additional_layer_data_key'
    CURRENT_FILM = 'current_film_key'
    CROPPED_TARGET_IMG = 'cropped_target_key'
    UPLOADED_TARGET_IMG = 'uploaded_target_key'
    TARGET_IMG_NAME = 'target_img_name_key'
    CROPPED_PIC = 'cropped_pic_key'
    USE_DEFAULT_TARGET_PIC = 'use_default_target_pic_key'
    PREVIOUS_PIXEL_COORDS = 'previous_pixel_coords_key'
    SELECTED_TARGETS = 'selected_targets_key'


class ChemicalElement(StrEnum):
    ASTATINE = 'At'
    FRANCIUM = 'Fr'
    FERMIUM = 'Fm'
    MENDELEVIUM = 'Md'
    NOBELIUM = 'No'
    LAWRENCIUM = 'Lr'
    RUTHERFORDIUM = 'Rf'
    DUBNIUM = 'Db'
    SEABORGIUM = 'Sg'
    BOHRIUM = 'Bh'
    HASSIUM = 'Hs'
    MEITNERIUM = 'Mt'
    DARMSTADTIUM = 'Ds'
    ROENTGENIUM = 'Rg'
    COPERNICIUM = 'Cn'
    NIHONIUM = 'Nh'
    FLEROVIUM = 'Fl'
    MOSCOVIUM = 'Mc'
    LIVERMORIUM = 'Lv'
    TENNESSINE = 'Ts'
    OGANESSON = 'Og'
    LITHIUM = 'Li'
    BERYLLIUM = 'Be'
    BORON = 'B'
    CARBON = 'C'
    SODIUM = 'Na'
    MAGNESIUM = 'Mg'
    ALUMINIUM = 'Al'
    SILICON = 'Si'
    PHOSPHORUS = 'P'
    SULFUR = 'S'
    POTASSIUM = 'K'
    CALCIUM = 'Ca'
    SCANDIUM = 'Sc'
    TITANIUM = 'Ti'
    VANADIUM = 'V'
    CHROMIUM = 'Cr'
    MANGANESE = 'Mn'
    IRON = 'Fe'
    COBALT = 'Co'
    NICKEL = 'Ni'
    COPPER = 'Cu'
    ZINC = 'Zn'
    GALLIUM = 'Ga'
    GERMANIUM = 'Ge'
    ARSENIC = 'As'
    SELENIUM = 'Se'
    RUBIDIUM = 'Rb'
    STRONTIUM = 'Sr'
    YTTRIUM = 'Y'
    ZIRCONIUM = 'Zr'
    NIOBIUM = 'Nb'
    MOLYBDENUM = 'Mo'
    TECHNETIUM = 'Tc'
    RUTHENIUM = 'Ru'
    RHODIUM = 'Rh'
    PALLADIUM = 'Pd'
    SILVER = 'Ag'
    CADMIUM = 'Cd'
    INDIUM = 'In'
    TIN = 'Sn'
    ANTIMONY = 'Sb'
    TELLURIUM = 'Te'
    IODINE = 'I'
    CAESIUM = 'Cs'
    BARIUM = 'Ba'
    LANTHANUM = 'La'
    CERIUM = 'Ce'
    PRASEODYMIUM = 'Pr'
    NEODYMIUM = 'Nd'
    PROMETHIUM = 'Pm'
    SAMARIUM = 'Sm'
    EUROPIUM = 'Eu'
    GADOLINIUM = 'Gd'
    TERBIUM = 'Tb'
    DYSPROSIUM = 'Dy'
    HOLMIUM = 'Ho'
    ERBIUM = 'Er'
    THULIUM = 'Tm'
    YTTERBIUM = 'Yb'
    LUTETIUM = 'Lu'
    HAFNIUM = 'Hf'
    TANTALUM = 'Ta'
    TUNGSTEN = 'W'
    RHENIUM = 'Re'
    OSMIUM = 'Os'
    IRIDIUM = 'Ir'
    PLATINUM = 'Pt'
    GOLD = 'Au'
    THALLIUM = 'Tl'
    LEAD = 'Pb'
    BISMUTH = 'Bi'
    POLONIUM = 'Po'
    RADIUM = 'Ra'
    ACTINIUM = 'Ac'
    THORIUM = 'Th'
    PROTACTINIUM = 'Pa'
    URANIUM = 'U'
    NEPTUNIUM = 'Np'
    PLUTONIUM = 'Pu'
    AMERICIUM = 'Am'
    CURIUM = 'Cm'
    BERKELIUM = 'Bk'
    CALIFORNIUM = 'Cf'
    EINSTEINIUM = 'Es'
    BROMINE = 'Br'
    MERCURY = 'Hg'
    HYDROGEN = 'H'
    HELIUM = 'He'
    NITROGEN = 'N'
    OXYGEN = 'O'
    FLUORINE = 'F'
    NEON = 'Ne'
    CHLORINE = 'Cl'
    ARGON = 'Ar'
    KRYPTON = 'Kr'
    XENON = 'Xe'
    RADON = 'Rn'

    @classmethod
    def from_short(cls, short: str) -> Self:
        return short_to_enum_elements[short]

    @staticmethod
    def all_short_str():
        return short_to_enum_elements.keys()


short_to_enum_elements = {
    element.value: element
    for element in ChemicalElement
}